"""models.py --version2.1.3 修改文件名字段非唯一"

Revision ID: 791b33d53092
Revises: 9ca82f962c27
Create Date: 2021-12-21 12:07:13.470724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791b33d53092'
down_revision = '9ca82f962c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('filename', table_name='paper')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('filename', 'paper', ['filename'], unique=True)
    # ### end Alembic commands ###
