"""models.py --version2.1.4 paper模型添加时间字段

Revision ID: 79bc51fba2cd
Revises: 791b33d53092
Create Date: 2021-12-26 10:50:42.994229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bc51fba2cd'
down_revision = '791b33d53092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'date')
    # ### end Alembic commands ###
