"""models.py --version2.1.3 添加paper模型路径字段

Revision ID: 9ca82f962c27
Revises: 421a50059617
Create Date: 2021-12-21 09:44:59.769028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca82f962c27'
down_revision = '421a50059617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('path', sa.String(length=265), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'path')
    # ### end Alembic commands ###
