"""models.py --version2.1.1, 添加教师，学生，课题之间的外键

Revision ID: c5ac4e48ef3b
Revises: 9cc23c397833
Create Date: 2021-12-13 00:38:40.634421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ac4e48ef3b'
down_revision = '9cc23c397833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'teachers', ['teacher_id'], ['id'])
    op.add_column('topics', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('topics', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topics', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'student_id')
    op.drop_column('topics', 'status')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'teacher_id')
    # ### end Alembic commands ###
